# 重要な処理

## 線形補間デモザイク

### 簡易デモザイク処理の問題点

簡易デモザイク処理を使ったRAW現像

```{r cache=TRUE}
raw_array <- raw$raw_image
white_level <- 1024

wb_raw <- raw_array %>%
  black_level_correction(raw$black_level_per_channel, raw$raw_pattern) %>%
  white_balance(raw$camera_whitebalance, raw$raw_colors)
dms_img <- wb_raw %>%
  simple_demosaic %>%
  `/`(white_level)
gmm_img <- gamma_correction(dms_img, 2.2)
```

表示

```{r cache=TRUE}
gmm_img %>% ta %>% as.cimg %>% plot
```

現像後のサイズ

```{r}
dim(gmm_img) %>% head(2)
```

RAWデータのサイズ

```{r}
dim(raw_array)
```

JPEG画像の読み込み

```{r}
jpg_img <- imager::load.image(raw_file)
```

拡大して比較

```{r cache=TRUE}
x1 <- 836
y1 <- 741
dx1 <- 100
dy1 <- 100

par(mfrow = c(1, 2))
gmm_img %>% ta %>% as.cimg %>%
  imsub(x %inr% c(x1, x1 + dx1), y %inr% c(y1, y1 + dy1)) %>%
  plot(interpolate = FALSE, main = "簡易デモザイク結果")
jpg_img %>%
  imsub(x %inr% (c(x1, x1 + dx1) * 2), y %inr% (c(y1, y1 + dy1) * 2)) %>%
  plot(interpolate = FALSE, main = "JPEG画像")
```

### 線形補完法

線形補間デモザイク

```{r}
demosaic <- function(raw_array, raw_colors, pattern) {
  dms_img <- array(0, c(dim(raw_array), 1, 3))

  g <- raw_array
  g[raw_colors %in% c(0, 2)] <- 0
  g_filter <- array(c(0, 1, 0,
                      1, 4, 1,
                      0, 1, 0) / 4,
                    c(3, 3, 1, 1))
  G(dms_img) <- convolve(as.cimg(g), g_filter)

  r <- raw_array
  r[raw_colors != 0] <- 0
  r_filter <- array(c(1/4, 1/2, 1/4,
                      1/2,   1, 1/2,
                      1/4, 1/2, 1/4),
                    c(3, 3, 1, 1))
  R(dms_img) <- convolve(as.cimg(r), r_filter)

  b <- raw_array
  b[raw_colors != 2] <- 0
  # 青のフィルターは赤と共通
  B(dms_img) <- convolve(as.cimg(b), r_filter)

  dms_img
}
```

デモザイク処理

```{r cache=TRUE}
dms_full_img <- wb_raw %>%
  demosaic(raw$raw_colors, raw$raw_pattern)
```

サイズを確認

```{r}
dms_full_img %>% dim %>% head(2)
```

ガンマ補正処理

```{r cache=TRUE}
gmm_full_img <- gamma_correction(dms_full_img / white_level, 2.2)
```

比較

```{r cache=TRUE}
par(mfrow = c(1, 2))
gmm_img %>% ta %>% as.cimg %>%
  imsub(x %inr% c(x1, x1 + dx1), y %inr% c(y1, y1 + dy1)) %>%
  plot(interpolate = FALSE, main = "簡易デモザイク")
gmm_full_img %>% ta %>% as.cimg %>%
  imsub(x %inr% (c(x1, x1 + dx1) * 2), y %inr% (c(y1, y1 + dy1) * 2)) %>%
  plot(interpolate = FALSE, main = "線形補間デモザイク")
```

## 欠陥画素補正

*TODO*

## カラーマトリクス補正

カラーマトリクス (CCM: Color Correction Matrix)

```{r}
color_matrix <- matrix(c(6022, -2314, 394,
                         -936, 4728, 310,
                         300, -4324, 8126),
                       3, 3, byrow = TRUE) / 4096
```

カラーマトリクス補正処理

```{r}
color_correction_matrix <- function(rgb_array, color_matrix) {
  ccm_img <- array(0, dim(rgb_array))
  for (col in 1:3) {
    ccm_img[,, 1, col] <-
      color_matrix[col, 1] * R(rgb_array) +
      color_matrix[col, 2] * G(rgb_array) +
      color_matrix[col, 3] * B(rgb_array)
  }
  ccm_img
}
```

比較

```{r cache=TRUE}
par(mfrow = c(1, 2))
gmm_full_img %>% ta %>% as.cimg %>%
  plot(main = "CCM補正なし")
dms_full_img %>%
  color_correction_matrix(color_matrix) %>%
  `/`(white_level) %>%
  gamma_correction(2.2) %>%
  ta %>% as.cimg %>% plot(main = "CCM補正あり")
```

## シェーディング補正

### レンズシェーディングの確認

RAW画像の読み込み

```{r}
raw_file <- "flat.jpg"
raw <- rawpy$imread(raw_file)
raw_array <- raw$raw_image
```

RAW現像処理

```{r cache=TRUE}
blc_raw <- raw_array %>%
  black_level_correction(raw$black_level_per_channel, raw$raw_pattern)
original_img <- blc_raw %>%
  white_balance(raw$camera_whitebalance, raw$raw_colors) %>%
  demosaic(raw$raw_colors, raw$raw_pattern) %>%
  color_correction_matrix(color_matrix) %>%
  `/`(white_level) %>%
  gamma_correction(2.2)
```

画像表示

```{r cache=TRUE}
original_img %>% ta %>% as.cimg %>% plot
```

明るさの横方向の変化

```{r message=FALSE}
library(tidyverse)

w <- ncol(raw_array)
h <- nrow(raw_array)
center_y <- h / 2
center_x <- w / 2
y <- center_y - 16

horizontal_shading_profile <- function(img, w, y) {
  seq(1, w - 32, 32) %>%
    map_dfr(function(x) list(r = mean(img[y:(y + 32), x:(x + 32), 1, 1]),
                             g = mean(img[y:(y + 32), x:(x + 32), 1, 2]),
                             b = mean(img[y:(y + 32), x:(x + 32), 1, 3]))) %>%
    map_dfr(~ . / max(.)) %>%
    mutate(pos = 1:n())
}
```

```{r cache=TRUE}
shading_profile <- horizontal_shading_profile(original_img, w, y)

ggplot(gather(shading_profile, "color", "value", -pos), aes(x = pos, y = value)) +
  geom_line(aes(color = color)) +
  ylim(0, 1) +
  scale_color_manual(values = c(r = "red", g = "green", b = "blue"))
```
